### ISSUE TITLE
Data Prep from tabular time series data

### ISSUE THREAD

**Issue by Manjubn777** [Keytoyze/VisionTS#1]
Hi team,
Great work; it looks very promising!
I am currently working on a time series project with data in tabular format. I would like to know if this package includes few shot,if so does this package includes functionality for converting tabular data to images. If not, how can I create images from tabular text data?  I have thousands of stores and hundreds of products, so saving line plots for each store-product combination is one option. Will this approach help my VisionTS model learn patterns more effectively and achieve better results than tabular-based models?

**Comment by Keytoyze** [comment]
Hi @Manjubn777 
Thank you for your inquiry!

VisionTS is a numerical forecasting model. You need to convert your tabular data into numerical sequences. Specifically, the input to VisionTS consists of a series of numerical values representing a length-$L$ historical window, and VisionTS will output their future forecast (length-$H$). You can refer to `demo.ipynb` for guidance on setting $H$ and $L$. You don't need to convert the numerical sequences into images, as we have already implemented it.

If you require few-shot fine-tuning, the `forward` method in the VisionTS module is differentiable, allowing for standard PyTorch backpropagation for tuning. By default, only the LayerNorm parameters will be updated. Notably, fine-tuning may not necessarily yield better results than zero-shot learning, as it depends on your scenario.

**Comment by Manjubn777** [comment]
That makes sense and I will try to replicate on my data. 
We have been trying few foundational models for our few QSR use cases however we have not got good results with zero shot and after fine tuning we did see a little improvement but again not better results than our current models. 

Thanks for your immediate response @Keytoyze I appreciate it.
