### ISSUE TITLE
Question about MSE of zero-shot experiment

### ISSUE THREAD

**Issue by LeonardoKong** [Keytoyze/VisionTS#2]
Hello! I have reproduced your zero-shot work on the ETTh1 dataset, but my MSE is 0.4416, while the MSE reported in your paper is around 0.35. What could be the reason for this discrepancy?

**Comment by Keytoyze** [comment]
Hi! Did you use the script in `long_term_tsf/scripts/vision_ts_zeroshot/ETTh1.sh`?

**Comment by LeonardoKong** [comment]
Sorry, I did not configure the seq_len to 2880. Thanks for your response.

**Comment by LeonardoKong** [comment]
The another issue is that when I use the official pre-trained MAE model by Kaiming He/Facebook Research, the results differ significantly from those in the paper. Is your MAE model the official one, or is it a version that has been pre-trained on time series data?

**Comment by Keytoyze** [comment]
VisionTS downloads the official checkpoint without training on time series. Please refer to https://github.com/Keytoyze/VisionTS/blob/main/visionts/model.py#L18.

One possible reason is that Kaiming provided two checkpoints for MAE. One contains decoder's weight (https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_base.pth) while the other disregards decoder (https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth). Did you use the later checkpoint?

**Comment by LeonardoKong** [comment]
Yes, I used the latter one and got a much larger MSE. Thanks for your explanation.
