### ISSUE TITLE
What's the ‘CONTEXT LEN = 2880’ meaning for?

### ISSUE THREAD

**Issue by RWLinno** [Keytoyze/VisionTS#4]
May I ask if all the results came out by fully learning such a long sequence length? Is it fair?

**Comment by Keytoyze** [comment]
@RWLinno Hi, we follow the recent setting of TSF foundation models to set a relatively long sequence length. For example, Moirai, one of the compared baselines, uses an even longer sequence length (5000) for ETTh1 (See [1]). One-fits-all [2] also argues that considering the context length as a tunable hyperparameter is reasonable (Appendix H.10, Page 32).

From another perspective, it is challenging for a model to predict a sequence with a length of up to 720 when the input window is very short (e.g., 60), especially in a zero-shot setting without training on time series data. Therefore, VisionTS requires a longer input window to capture the patterns in the input, enabling accurate long-term forecasting.

[1] https://github.com/SalesforceAIResearch/uni2ts/blob/main/project/moirai-1/eval/lsf_small.sh#L6

[2] https://arxiv.org/pdf/2302.11939

**Comment by Zero-coder** [comment]
Hello this Context_length is more like pure input, or like cloze , eg {x1,x2,x3,[mask],x5,[mask]}?
and one more question hyperparameter c determine the visible patch n, does this influence prediction length? thanks for your work

**Comment by Zero-coder** [comment]
when predict 96,192,336,720 ,how matain this prediction length?
