### ISSUE TITLE
显存占用问题

### ISSUE THREAD

**Issue by Harryx2019** [Keytoyze/VisionTS#5]
非常感激作者的工作，对我们的研究有很大的启发。不过我们在微调模型的过程中遇到了一些问题，模型在finetune阶段占用的显存是zeroshot的两倍，请问出现这个问题的原因是什么？另外请问你们的微调代码在哪里？

**Comment by Keytoyze** [comment]
感谢关注！
- finetune阶段需要额外储存一些优化器状态，所以显存占用比zero-shot更大。
- 我们的VisionTS可以集成到任何的训练框架里。具体来说，论文使用了Time-Series-Library，运行脚本在 `long_term_tsf/scripts/vision_ts_fullshot/`下面。
