### ISSUE TITLE
zero-shot精度比one-shot更高

### ISSUE THREAD

**Issue by liujian123223** [Keytoyze/VisionTS#6]
您好，我在使用zero-shot的过程中可以获得很高的精度，但是当我进行训练时，经常会出现loss无法降低的情况，也就是第一个epoch精度最高。有时候还会遇到one-shot精度比zero-shot更低，且随着训练epoch越多精度越低。你能为我解答这个问题吗？谢谢。

如果我希望在zero-shot的基础上进一步提升精度那我应该怎么办呢?我目前使用论文默认的ln微调

**Comment by Keytoyze** [comment]
你好，请问数据量是多少呢？看起来可能是过拟合。论文中ETTh1和ETTh2也是有类似的现象的，因为样本数量过少。

**Comment by liujian123223** [comment]
我的训练样本大约12000，设置的seq_len为7100。请问要多少样本量才合适呢？或者你有什么建议吗？

**Comment by Keytoyze** [comment]
可以试试把seq_len调小，因为这么大的seq_len可能导致训练样本数过少。我们也发现full-shot实验中的seq_len需要比zero-shot小一点，这样才能增多训练样本。

**Comment by liujian123223** [comment]
好的，我会试一下，之所以seq_len这么大，也是超参数搜索得到的。我以为进行训练时7100也会带来更好的结果
